"""Machine-readable expression provenance for ChatSpatial datasets.

ChatSpatial datasets can hold either a measured expression matrix or a matrix
generated by a model from another modality. Both live in ``adata.X``, so the
distinction has to be recorded in metadata rather than inferred from the values.
A predicted log1p-CPM matrix is dense, non-negative, and continuous, which is
exactly what a heuristic count detector reads as "already normalized measured
data". That is why every guard in this module runs before any value-based
inspection.

The generic semantics live in ``adata.uns["chatspatial"]["expression"]`` and stay
backend independent:

.. code-block:: python

    {
        "schema_version": 1,
        "provenance": "predicted",
        "units": "log1p_cpm",
        "producer": "deepspotm",
    }

Backend-specific detail (model repository, checkpoint revision, licensing, and
so on) belongs in its own top-level ``adata.uns`` entry, keyed by producer.

Tools should never test for a particular producer. They ask whether the matrix
is predicted, and refuse or proceed accordingly:

.. code-block:: python

    reject_predicted_expression(
        adata,
        operation="preprocess_data",
        reason="count-based normalization is undefined for this matrix",
        guidance="Run compute_embeddings directly.",
    )
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Optional

from .exceptions import DataCompatibilityError, ParameterError

if TYPE_CHECKING:  # pragma: no cover - typing only
    import anndata as ad

# Namespace that holds ChatSpatial's own generic dataset semantics.
CHATSPATIAL_UNS_KEY = "chatspatial"
EXPRESSION_UNS_KEY = "expression"

# Version of the expression metadata block itself, not of any model.
EXPRESSION_SCHEMA_VERSION = 1

# Provenance values. "measured" describes an assay readout; "predicted"
# describes a matrix generated by a model from another modality.
PROVENANCE_MEASURED = "measured"
PROVENANCE_PREDICTED = "predicted"

# Units understood by the guards below.
UNITS_LOG1P_CPM = "log1p_cpm"

_VALID_PROVENANCE = (PROVENANCE_MEASURED, PROVENANCE_PREDICTED)


def set_expression_provenance(
    adata: "ad.AnnData",
    *,
    provenance: str,
    units: str,
    producer: str,
    schema_version: int = EXPRESSION_SCHEMA_VERSION,
) -> dict[str, Any]:
    """Record generic expression semantics for ``adata.X``.

    Args:
        adata: Dataset to annotate in place.
        provenance: ``"measured"`` or ``"predicted"``.
        units: Value scale of ``adata.X``, for example ``"log1p_cpm"``.
        producer: Identifier of the tool or model that wrote ``adata.X``.
        schema_version: Version of this metadata block.

    Returns:
        The stored expression metadata dictionary.

    Raises:
        ParameterError: If ``provenance`` is not a recognized value.
    """
    if provenance not in _VALID_PROVENANCE:
        raise ParameterError(
            f"Unknown expression provenance {provenance!r}. "
            f"Expected one of: {', '.join(_VALID_PROVENANCE)}."
        )

    namespace = adata.uns.get(CHATSPATIAL_UNS_KEY)
    if not isinstance(namespace, dict):
        namespace = {}

    metadata = {
        "schema_version": int(schema_version),
        "provenance": provenance,
        "units": units,
        "producer": producer,
    }
    namespace = dict(namespace)
    namespace[EXPRESSION_UNS_KEY] = metadata
    adata.uns[CHATSPATIAL_UNS_KEY] = namespace
    return metadata


def get_expression_metadata(adata: Any) -> Optional[dict[str, Any]]:
    """Return the expression metadata block, or ``None`` when it is absent.

    Datasets written before this metadata existed, and datasets loaded from
    external files, carry no block at all. Those are treated as unannotated
    rather than as predicted, so existing workflows keep working unchanged.
    """
    uns = getattr(adata, "uns", None)
    if uns is None:
        return None

    try:
        namespace = uns.get(CHATSPATIAL_UNS_KEY)
    except AttributeError:  # pragma: no cover - defensive
        return None

    if not isinstance(namespace, dict):
        return None

    metadata = namespace.get(EXPRESSION_UNS_KEY)
    if not isinstance(metadata, dict):
        return None
    return metadata


def get_expression_provenance(adata: Any) -> Optional[str]:
    """Return the declared provenance of ``adata.X``, or ``None`` if undeclared."""
    metadata = get_expression_metadata(adata)
    if metadata is None:
        return None
    provenance = metadata.get("provenance")
    return provenance if isinstance(provenance, str) else None


def is_predicted_expression(adata: Any) -> bool:
    """Return whether ``adata.X`` is declared as model-predicted expression."""
    return get_expression_provenance(adata) == PROVENANCE_PREDICTED


def _describe_predicted_expression(adata: Any) -> str:
    """Describe a predicted matrix for an error message."""
    metadata = get_expression_metadata(adata) or {}
    producer = metadata.get("producer") or "an unnamed producer"
    units = metadata.get("units") or "unspecified units"
    return f"{units} predicted by {producer}"


def reject_predicted_expression(
    adata: Any,
    *,
    operation: str,
    reason: str,
    guidance: str,
) -> None:
    """Raise when ``adata.X`` holds predicted expression.

    This is the single shared guard. Call it before any value-based inspection
    of the matrix, so a predicted matrix never reaches a heuristic that would
    classify it as measured data.

    Args:
        adata: Dataset to inspect.
        operation: Public name of the operation being refused.
        reason: Why the operation is invalid for predicted expression.
        guidance: The concrete next step for the user.

    Raises:
        DataCompatibilityError: If ``adata.X`` is declared predicted.
    """
    if not is_predicted_expression(adata):
        return

    raise DataCompatibilityError(
        f"{operation} is not available for this dataset: "
        f"adata.uns['{CHATSPATIAL_UNS_KEY}']['{EXPRESSION_UNS_KEY}'] declares "
        f"{_describe_predicted_expression(adata)}, so the dataset carries no "
        f"measured expression matrix. {reason} {guidance}"
    )
